package Enum;

public enum AccountType {
	REGULAR_ACCOUNT,
	REGULAR_ACCOUNT_INTEREST,
	FOREIGN_ACCOUNT_USD,
	FOREIGN_ACCOUNT_USD_INTEREST,
	FOREIGN_ACCOUNT_EUR,
	FOREIGN_ACCOUNT_EUR_INTEREST,
	GOLD_ACCOUNT,
	GOLD_ACCOUNT_INTEREST,
	INVESTMENT_ACCOUNT
}
